

import React from "react";
import styles from "./register.module.css";
import RegisterForm from "@/components/registerForm/registerForm";
export const metadata = {
  title: "register page",
  description: "Generated by create next app",
};

const Register = () => {
  return (
    <div className={styles.container}>
      <div className={styles.wrapper}>
        <RegisterForm/>
      </div>
    </div>
  );
};

export default Register;
