import LoginForm from "@/components/loginForm/loginForm";
import styles from "./login.module.css";
import { handleGithubLogin } from "@/lib/action";

export const metadata = {
  title: "login page",
  description: "Generated by create next app",
};

const Login = () => {
  return (
    <div className={styles.container}>
      <div className={styles.wrapper}>
        <form>
          <button className={styles.github} formAction={handleGithubLogin}>login with github</button>
        </form>
        <LoginForm />
      </div>
    </div>
  );
};

export default Login;
